version: '3'
services:
  
    nginx:
        container_name: nginx-container        
        build: ./nginx
        restart: always
        ports:
        - "8080:80" 
        volumes:        
        - api_data:/docker_api        
        - ./log:/var/log/nginx              
        depends_on:
        - api
        
    api:
        container_name: api-container
        build: ./RestApi        
        restart: always
        # command: uwsgi  --emperor uwsgi.ini         
        command: uwsgi --ini uwsgi.ini         
        ports:
        - "8002:8000"
        volumes:
        - api_data:/docker_api        
        

volumes:
    api_data:
    pgdata:
