# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-05 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artilcle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('art_desc', models.TextField(max_length=10000, verbose_name='内容')),
                ('art_type', models.IntegerField(choices=[(1, '编程'), (2, '生活')], help_text='分类', verbose_name='文章分类')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('is_origin', models.BooleanField(default=True, verbose_name='是否原创')),
            ],
            options={
                'verbose_name': '文章',
                'db_table': 'blog_article',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.AddField(
            model_name='artilcle',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Label', verbose_name='商品标签'),
        ),
    ]
