# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180605_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='artilcle',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='是否在首页显示'),
        ),
    ]
