# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_artilcle_is_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.CharField(max_length=50, verbose_name='首页codes')),
                ('shares', models.CharField(max_length=50, verbose_name='首页shares')),
            ],
            options={
                'verbose_name_plural': '首页数据',
                'verbose_name': '首页数据',
            },
        ),
    ]
