# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_homedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedata',
            name='name',
            field=models.CharField(default='首页数据', max_length=50, verbose_name='名字'),
        ),
    ]
