# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-08 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_homedata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='图片描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/images/%Y/%m', verbose_name='博客图片')),
            ],
            options={
                'verbose_name': '博客图片',
                'verbose_name_plural': '博客图片',
            },
        ),
    ]
