# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-08 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='name',
        ),
    ]
