# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_task_taskimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Task', verbose_name='测试模型'),
        ),
    ]
